when:
  branch: main
  event: push

steps:
  build:
    image: woodpeckerci/plugin-kaniko
    settings:
      password:
        from_secret: docker_password
      repo: martyo/cloudserve-landing
      tags:
        - latest
      username:
        from_secret: docker_username
