when:
  branch: main
  event: push

steps:
  build:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: https://git.martyoeh.me
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hosting/martyoeh.me
      tags:
        - latest
